# tcs_demo
name: 01-Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Hello
        run: echo "Hello World"
      - name: Print Multiple Lines
        run: |
          echo "Hi"
          echo "Hello : $RUNNER_OS"
          echo "which git : $GITHUB_REPOSITORY"
          echo "RUNNER_OS: $RUNNER_OS"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
